Repository MolSSI/molssi-hub, pull requests merged in 2023-05, with the labels that each got.

#1 Adds a first batch of Dockerfiles
  README.md
  docs/acknowledgements.rst
  docs/buildDocs.sh
  docs/compchem/index.rst
  docs/compchem/pyscf.rst
  docs/conf.py
  docs/general/index.rst
  docs/general/mamba.rst
  docs/general/micromamba.rst
  docs/general/miniconda3.rst
  docs/images/docker.svg
  docs/index.rst
  docs/machine_learning/torchani.rst
  docs/machine_learning/torchani_dev.rst
  docs/quick_start.rst
  molssiai_hub/__init__.py
  molssiai_hub/_version.py
  molssiai_hub/base/debian-bullseye-slim-dev/Dockerfile
  molssiai_hub/compchem/pyscf/Dockerfile
  molssiai_hub/general/mamba/Dockerfile
  molssiai_hub/general/micromamba/Dockerfile
  molssiai_hub/general/miniconda3/Dockerfile
  molssiai_hub/machine_learning/torchani/Dockerfile
  molssiai_hub/machine_learning/torchani/metadata.json
Labels: enhancement

#2 Adds the CI GHActions for Docs
  .github/workflows/Docs.yaml
Labels: documentation

#3 Adds the environment.txt file for dependencies
  docs/Makefile
  requirements.txt
Labels: documentation, enhancement

#5 Adds looping capability up to two nested levels for catalogs' metadata
  docs/_templates/catalog.rst
  molssiai_hub/compchem/pyscf/metadata.json
  molssiai_hub/machine_learning/torchani/metadata.json
Labels: documentation, enhancement

#6 Adds a series of metadata for general Dockerfiles
  metadata_template.json
  molssiai_hub/compchem/pyscf/metadata.json
  molssiai_hub/general/mamba/metadata.json
  molssiai_hub/general/micromamba/metadata.json
  molssiai_hub/general/miniconda3/metadata.json
Labels: documentation, enhancement

#7 adds the new MolSSI-AI logo and minor changes
  docs/_static/molssi_ai.png
  docs/_static/molssi_ai.svg
  docs/conf.py
  docs/index.rst
Labels: documentation, enhancement

#8 Adds Dockerfile and metadata for PSI4
  MANIFEST.in
  README.md
  docs/__init__.py
  docs/compchem/index.rst
  docs/conf.py
  docs/json2jinja.py
  molssiai_hub/__init__.py
  molssiai_hub/compchem/psi4_mamba141_py310/Dockerfile
  molssiai_hub/compchem/psi4_mamba141_py310/metadata.json
Labels: documentation, enhancement

#9 Makes folder names consistent with Dockerhub repos
  docs/_templates/catalog.rst
  docs/compchem/index.rst
  docs/general/index.rst
  docs/json2jinja.py
  docs/machine_learning/index.rst
  molssiai_hub/compchem/psi4v18-mamba141-py310/Dockerfile
  molssiai_hub/compchem/psi4v18-mamba141-py310/metadata.json
  molssiai_hub/compchem/pyscf221-base-mamba141-jupyter/Dockerfile
  molssiai_hub/compchem/pyscf221-base-mamba141-jupyter/metadata.json
  molssiai_hub/general/mamba141/Dockerfile
  molssiai_hub/general/mamba141/metadata.json
  molssiai_hub/general/micromamba142-py310/Dockerfile
  molssiai_hub/general/micromamba142-py310/metadata.json
  molssiai_hub/machine_learning/torchani223-cu117-ase-mamba141-jupyter/Dockerfile
  molssiai_hub/machine_learning/torchani223-cu117-ase-mamba141-jupyter/metadata.json
Labels: documentation, enhancement

#11 Adds the contributions page
  CONTRIBUTING.rst
  docs/contribute.rst
  docs/dev_team.rst
  docs/index.rst
Labels: documentation

#12 Adds minor chanages
  docs/contribute.rst
  docs/quick_start.rst
Labels: documentation

#13 fixes the GitHub icon link in the documentation
  docs/conf.py
Labels: bug, documentation

#14 adds the new files for MOPAC 22.0.6
  docs/compchem/index.rst
  molssiai_hub/compchem/mopac2206-mamba141/Dockerfile
  molssiai_hub/compchem/mopac2206-mamba141/metadata.json
  molssiai_hub/compchem/psi4v18-mamba141-py310/metadata.json
  molssiai_hub/compchem/pyscf221-base-mamba141-jupyter/metadata.json
  molssiai_hub/general/mamba141/metadata.json
  molssiai_hub/general/micromamba142-py310/metadata.json
  molssiai_hub/machine_learning/torchani223-cu117-ase-mamba141-jupyter/metadata.json
Labels: documentation, enhancement

#16 Adds the default volume mounting option to the docker run command
  docs/_templates/catalog.rst
  docs/base/debian-bullseye-slim-dev.rst
  docs/compchem/mopac2206-mamba141.rst
  docs/compchem/psi4v18-mamba141-py310.rst
  docs/compchem/pyscf221-base-mamba141-jupyter.rst
  docs/conf.py
  docs/contribute.rst
  docs/general/mamba141.rst
  docs/general/micromamba142-py310.rst
  docs/general/miniconda3.rst
  docs/index.rst
  docs/machine_learning/torchani223-cu117-ase-mamba141-jupyter.rst
  metadata_template.json
  molssiai_hub/base/debian-bullseye-slim-dev/metadata.json
  molssiai_hub/compchem/mopac2206-mamba141/metadata.json
  molssiai_hub/compchem/psi4v18-mamba141-py310/metadata.json
  molssiai_hub/compchem/pyscf221-base-mamba141-jupyter/metadata.json
  molssiai_hub/general/mamba141/metadata.json
  molssiai_hub/general/micromamba142-py310/metadata.json
  molssiai_hub/general/miniconda3/metadata.json
  molssiai_hub/machine_learning/torchani223-cu117-ase-mamba141-jupyter/metadata.json
Labels: documentation, enhancement

#17 adds a PSI4 example
  docs/compchem/index.rst
  docs/compchem/psi4_example.rst
Labels: documentation, enhancement

#19 Adds the Pytorch Image and Apptainer usage for Psi4
  docs/compchem/psi4_example.rst
  docs/machine_learning/index.rst
  docs/machine_learning/pytorch201-cu117-mamba141.rst
  docs/machine_learning/torchani_dev.rst
  molssiai_hub/machine_learning/pytorch201-cu117-mamba141/Dockerfile
  molssiai_hub/machine_learning/pytorch201-cu117-mamba141/metadata.json
Labels: documentation, enhancement
